CREATE TABLE "APP"."USERS"
(
   USER_ID int PRIMARY KEY NOT NULL,
   USERNAME varchar(45) NOT NULL,
   PASSWORD varchar(45) NOT NULL,
   ENABLED smallint NOT NULL
)
;
CREATE UNIQUE INDEX SQL120531111556000 ON "APP"."USERS"(USER_ID)
;